[package]
name = "teamserver"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.87"
env_logger = "0.11.5"
clap = { version = "4.5.17", features = ["derive"] }
log = "0.4.22"
rand = "0.8.5"
rsa = "0.9.6"